receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:
    verbosity: Detailed

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging ]