version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:1.24-bullseye
    depends_on:
      - broker
    env_file: devcontainer.env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity